## Упражнения по библиотеке Numpy

In [29]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [43]:
def change_sign(rand_arr):
    mask = (rand_arr >= 3) & (rand_arr <= 8)
    rand_arr[mask] *= -1
    return rand_arr

random_array = np.random.randint(low=-10, high=10, size=(np.random.randint(1,10), np.random.randint(1,10)))
print('Initial matrix')
print(random_array)
print('Result matrix')
print(change_sign(random_array))

Initial matrix
[[-10   1  -1   6]
 [ -6  -1   7  -3]]
Result matrix
[[-10   1  -1  -6]
 [ -6  -1  -7  -3]]


**2.** Заменить максимальный элемент случайного массива на 0

In [60]:
def change_max_el(rand_arr):
    mask = rand_arr == np.max(rand_arr)
    rand_arr[mask] = 0
    return rand_arr

random_array = np.random.randint(low=-10, high=10, size=(np.random.randint(1,10), np.random.randint(1,10)))
print('Initial matrix')
print(random_array)
print('Result matrix')
print(change_max_el(random_array))

Initial matrix
[[ 8  4  0  8  1 -6 -9]
 [-4 -2 -2  6  0 -4 -8]
 [ 4 -5 -8 -1 -3 -1 -6]]
Result matrix
[[ 0  4  0  0  1 -6 -9]
 [-4 -2 -2  6  0 -4 -8]
 [ 4 -5 -8 -1 -3 -1 -6]]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [66]:
random_array = np.random.randint(low=-10, high=10, size=(2, np.random.randint(1,10)))
res_array = np.outer(random_array[0, :], random_array[1, :])
print('Initial matrix')
print(random_array)
print('Result matrix')
print(res_array)

[[ -4   3 -10   8   8  -6]
 [ -8   9   3   9   0  -3]]
[[ 32 -36 -12 -36   0  12]
 [-24  27   9  27   0  -9]
 [ 80 -90 -30 -90   0  30]
 [-64  72  24  72   0 -24]
 [-64  72  24  72   0 -24]
 [ 48 -54 -18 -54   0  18]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [129]:
def is_in(a, b):
    result_rows = []
    for row in range(len(a)):
        if np.any(np.isin(b[0], a[row])) and np.any(np.isin(b[1], a[row])):
            result_rows.append(row + 1)
    return result_rows

random_array_a = np.random.randint(low=0, high=10, size=(8, 3))
random_array_b = np.random.randint(low=0, high=10, size=(2, 2))
print('Initial matrix A')
print(random_array_a)
print('Initial matrix B')
print(random_array_b)
print(f'Result(list of rows, first row = 1): {is_in(random_array_a, random_array_b)}')

Initial matrix A
[[4 1 3]
 [5 4 1]
 [5 0 8]
 [0 3 6]
 [3 9 6]
 [3 0 9]
 [2 5 0]
 [4 7 3]]
Initial matrix B
[[5 8]
 [6 0]]
Result(list of rows, first row = 1): [3, 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [131]:
random_array = np.random.choice(np.arange(4), size=(10, 3), p=[0.03, 0.03, 0.47, 0.47])
res_array = random_array[~np.all(random_array[:, 1:] == random_array[:, :-1], axis=1)]
print('Initial matrix')
print(random_array)
print('Result matrix')
print(res_array)

Initial matrix
[[2 3 2]
 [3 3 3]
 [2 3 2]
 [2 2 2]
 [3 3 2]
 [3 2 2]
 [3 3 2]
 [2 2 2]
 [2 3 2]
 [3 1 1]]
Result matrix
[[2 3 2]
 [2 3 2]
 [3 3 2]
 [3 2 2]
 [3 3 2]
 [2 3 2]
 [3 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [194]:
random_array = np.random.choice(np.arange(4), size=(10, 3), p=[0.03, 0.03, 0.47, 0.47])
res_array = np.unique(random_array, axis=0)
print('Initial matrix')
print(random_array)
print('Result matrix')
print(res_array)

Initial matrix
[[3 2 3]
 [3 2 3]
 [2 2 2]
 [2 2 3]
 [2 3 3]
 [3 2 2]
 [3 2 3]
 [3 0 3]
 [2 3 3]
 [3 3 3]]
Result matrix
[[2 2 2]
 [2 2 3]
 [2 3 3]
 [3 0 3]
 [3 2 2]
 [3 2 3]
 [3 3 3]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [30]:
# realization with numpy
def diagonal_product(matrix):
    diagonal = np.diagonal(matrix)
    mask = ~(diagonal == 0)
    res = np.prod(diagonal[mask])
    return res
    
random_array = np.random.randint(low=0, high=10, size=(np.random.randint(1, 10), np.random.randint(1,10)))
print('Initial matrix')
print(random_array)
print(f'Result(product of diagonal not null elements): {diagonal_product(random_array)}')

Initial matrix
[[9 9 1 7 7 9]
 [1 3 8 8 3 2]
 [1 9 9 5 7 7]
 [5 3 3 1 2 2]
 [0 0 0 7 8 1]
 [3 7 2 8 7 7]
 [3 9 0 0 8 5]
 [8 4 6 1 9 5]
 [1 9 0 0 0 1]]
Result(product of diagonal not null elements): 13608


In [31]:
# realization without numpy
from random import randint

def diagonal_product(matrix):
    res = 1
    for row in range(len(matrix)):
        for column in range(len(matrix[row])):
            if row == column and matrix[row][column] != 0:
                res *= matrix[row][column]
    return res

matrix = [[randint(0,5) for _ in range(5)] for _ in range(randint(1,10))]
print('Initial matrix')
print(*matrix, sep='\n')
print(f'Result(product of diagonal not null elements): {diagonal_product(matrix)}')
            

Initial matrix
[2, 3, 2, 4, 1]
[3, 2, 3, 2, 5]
[2, 3, 2, 4, 1]
Result(product of diagonal not null elements): 8


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [94]:
# realization with numpy
def same_multiset(v_x, v_y):
    sorted_x = np.sort(v_x)
    sorted_y = np.sort(v_y)
    res = (len(sorted_x) == len(sorted_y) and (np.all(np.equal(sorted_x, sorted_y))))
    return res

vector_x = np.random.randint(low=0, high=10, size=(np.random.randint(1,10))) 
vector_y = np.random.randint(low=0, high=10, size=(np.random.randint(1,10)))
print(f'Vector x = {vector_x}, Vector y = {vector_y}')
print(f'Result(is same multiset): {same_multiset(vector_x, vector_y)}')

Vector x = [5 6 3 3 8 7 7 1 8], Vector y = [4 8 9 9 7 1]
Result(is same multiset): False


In [66]:
# realization without numpy
def same_multiset(v_x, v_y):
    res = True
    if len(set(v_x)) != len(set(v_x)):
        res = False
    else:
        for i in set(v_x):
            if v_x.count(i) != v_y.count(i):
                res = False
                break
    return res

vector_x = [randint(0,5) for _ in range(randint(1, 10))]
vector_y = [randint(0,5) for _ in range(randint(1, 10))]
print(f'Vector x = {vector_x}, Vector y = {vector_y}')
print(f'Result(is same multiset): {same_multiset(vector_x, vector_y)}')

Vector x = [2, 0, 1, 5, 4, 5, 5, 4], Vector y = [2, 1, 5, 4, 5, 4, 5, 2]
Result(is same multiset): False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [137]:
# realization with numpy
def max_el_after_0(matrix):
    mask = np.roll(matrix == 0, 1)
    res = np.max(matrix.astype(float), where=mask, initial=-np.inf)
    return res
    
matrix = np.random.randint(low=0, high=10, size=(np.random.randint(2,10)))
print(f'Initial matrix: {matrix}')
print(f'Result: {max_el_after_0(matrix)}')

Initial matrix: [9 5]
Result: -inf


In [175]:
# realization without numpy
def max_el_after_0(matrix):
    el_list = []
    for i in range(1, len(matrix)):
        if matrix[i - 1] == 0:
            el_list.append(matrix[i])
    if len(el_list) == 0:
        return 'No such elements'
    return max(el_list)
    
matrix = [randint(0,5) for _ in range(randint(3,10))]
print(f'Initial matrix: {matrix}')
print(f'Result: {max_el_after_0(matrix)}')

Initial matrix: [4, 0, 1]
Result: 1


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [174]:
# realization with numpy
matrix = np.random.randint(low=0, high=10, size=(np.random.randint(2,10)))
print(f'Initial matrix: {matrix}')
print(f'Result: {np.unique(matrix, return_counts=True)}')

Initial matrix: [7 8]
Result: (array([7, 8]), array([1, 1], dtype=int64))


In [236]:
# realization without numpy
def run_lenth_encoding(matrix):
    res = {}
    for i in matrix:
        res[i] = res.get(i, 0) + 1
    return list(res.keys()), list(res.values())

matrix = [randint(0,5) for _ in range(randint(3,10))]
print(f'Initial matrix: {matrix}')
print(f'Result: {run_lenth_encoding(matrix)}')

Initial matrix: [5, 5, 3, 0, 5, 4, 2]
Result: ([5, 3, 0, 4, 2], [3, 1, 1, 1, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [304]:
# realization with numpy
from time import time 
def euclidean_distance(objects_x, objects_y):
    distance = np.sqrt(np.sum((objects_x[:, np.newaxis]-objects_y) ** 2, axis=-1))
    return distance

objects_x = np.random.randint(low=0, high=10, size=(3, 2)) 
objects_y = np.random.randint(low=0, high=10, size=(3, 2))

start_time = time()
distances = euclidean_distance(objects_x, objects_y)
end_time = time()
running_time = (end_time - start_time) 

print(f'Objects X: \n{objects_x}\nObjects Y: \n{objects_y}')
print(f'Result: \n{distances} \nRunning time: {running_time:.25f}')

Objects X: 
[[0 2]
 [7 7]
 [7 6]]
Objects Y: 
[[4 7]
 [2 0]
 [4 2]]
Result: 
[[6.40312424 2.82842712 4.        ]
 [3.         8.60232527 5.83095189]
 [3.16227766 7.81024968 5.        ]] 
Running time: 0.0000000000000000000000000


In [305]:
# realization without numpy
from scipy.spatial.distance import cdist

objects_x = [list(i) for i in objects_x]
objects_y = [list(i) for i in objects_y]

start_time = time()
distances = cdist(objects_x, objects_y, metric='euclidean')
end_time = time()
running_time = (end_time - start_time) 

print(f'Objects X: {objects_x}, Objects Y: {objects_y}')
print(f'Result: \n{distances} \nRunning time: {running_time:.25f}')

Objects X: [[0, 2], [7, 7], [7, 6]], Objects Y: [[4, 7], [2, 0], [4, 2]]
Result: 
[[6.40312424 2.82842712 4.        ]
 [3.         8.60232527 5.83095189]
 [3.16227766 7.81024968 5.        ]] 
Running time: 0.0000000000000000000000000


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [254]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [258]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [260]:
average_calories = np.average(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [261]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [262]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [281]:
nth_percentile = 3.3
np.percentile(calorie_stats_sorted, nth_percentile)

60.16

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [283]:
more_calories = 100 - nth_percentile 
more_calories

96.7

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [284]:
calorie_std = np.std(calorie_stats_sorted)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
# Как по мне, самая полезная цифра тут - 96,7%, которая показывает то, у скольких конкурентов калорийность выше. Думаю, в маркетинговой компании стоит
# делать упор именно на неё, также стоит отметить, что исследование было провдено среди 77 конкурентов. Можно как-то попробовать обыграть, что среднее 
# значение составляет 106, при этом чаще всего на полках встречаются продукты со 110.0 каллориями и выше.

# что-то в таком духе
# Откройте для себя новый путь к здоровому образу жизни с CrunchieMunchies!
# После тщательного анализа 77 популярных брендов хлопьев мы обнаружили, что удивительные 96,7% из них оказались калорийнее, чем можно было предположить.
# И здесь особенно интересный момент: средняя калорийность на полках составляет 106, а чаще всего встречаются продукты со 110.0 калориями и выше.
# В ответ на это мы создали CrunchieMunchies - вкусные и полезные злаки с калорийностью всего 60 калорий в порции. Наши злаки станут легким шагом к вашему здоровью.
# Не упустите возможность попробовать CrunchieMunchies и перейти на новый уровень заботы о себе!